POST  http://localhost:4000/app/signup
Content-Type: application/json

{
    "fullName" : "Joseph",
    "username" : "joey",
    "email"    : "joe123@gmail.com",
    "password" : "joey12333"
}
       